name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - v**
jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # service: ["order", "payment", "shipping"]
        service: ["order"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - uses: actions/checkout@v4
      - name: Etract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Generate for Golang"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/protoc.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./protoc.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com